SecurityWebApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SecurityWebApp.Attributes;
using SecurityWebApp.Data;
using SecurityWebApp.Data.Model;

namespace SecurityWebApp.Controllers
{
  [Roles(DefaultRoles.Max)]
  public class AdminController : Controller
  {
    private readonly ApplicationDbContext _context;
    private readonly ILogger<AdminController> _logger;
    private readonly UserManager<AppUser> _userManager;
    private readonly SignInManager<AppUser> _signManager;

    public AdminController(ApplicationDbContext context, ILogger<AdminController> logger, UserManager<AppUser> userManager, SignInManager<AppUser> signManager)
    {
      _context = context;
      _logger = logger;
      _userManager = userManager;
      _signManager = signManager;
    }
    public async Task<IActionResult> Index() => View(await _context.Users.ToListAsync());

    public async Task<IActionResult> Delete(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var user = await _context.Users
          .FirstOrDefaultAsync(m => m.Id == id.Value.ToString());

      if (user == null)
      {
        return NotFound();
      }

      return View(user);
    }

    [HttpPost]
    public async Task<IActionResult> DeleteConfirmed(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var user = await _context.Users
          .FirstOrDefaultAsync(m => m.Id == id.Value.ToString());

      try
      {
        if (user.UserName.Equals(HttpContext.User.Identity.Name.ToString()))
          await _signManager.SignOutAsync();

        await _userManager.DeleteAsync(user);
      }
      catch (Exception)
      {
        return View("Error");
      }

      return RedirectToAction(nameof(Index));
    }
  }
}

SecurityWebApp/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Log.Core.Model;
using Log.Core.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SecurityWebApp.Attributes;
using SecurityWebApp.Data;
using SecurityWebApp.Data.Model;
using SecurityWebApp.Models;

namespace SecurityWebApp.Controllers
{
  [Roles(DefaultRoles.Max)]
  public class LogController : Controller
  {
    private readonly IRepository _rep;
    private readonly IRepositoryLog _repLog;

    public LogController(IRepository rep, IRepositoryLog repLog)
    {
      _rep    = rep;
      _repLog = repLog;
    }

    public async Task<IActionResult> Index(FilterLogDTO filter)
    {
      var logs = await _repLog.GetByFilterLog(filter);

      return View(new LogViewModel
      {
        Logs      = logs,
        DateEnd   = filter.DateEnd,
        DateStart = filter.DateStart,
        Text      = filter.Text
      });
    }
  }
}

SecurityWebApp/Controllers/PilotsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SecurityWebApp.Attributes;
using SecurityWebApp.Data;
using SecurityWebApp.Data.Model;

namespace SecurityWebApp.Controllers
{
  [Authorize]
  public class PilotsController : Controller
  {
    private readonly ApplicationDbContext _context;

    public PilotsController(ApplicationDbContext context)
    {
      _context = context;
    }


    public async Task<IActionResult> Index()
    {
      return View(await _context.Pilots.ToListAsync());
    }

    [Roles(DefaultRoles.Max)]
    public IActionResult Create()
    {
      return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    [Roles(DefaultRoles.Max)]
    public async Task<IActionResult> Create([Bind("Id,Name,BirthDate,Genre")] Pilot pilot)
    {
      if (ModelState.IsValid)
      {
        pilot.Id = Guid.NewGuid();
        _context.Add(pilot);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }
      return View(pilot);
    }

    [Roles(DefaultRoles.Max, DefaultRoles.Med)]
    public async Task<IActionResult> Edit(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var pilot = await _context.Pilots.FindAsync(id);
      if (pilot == null)
      {
        return NotFound();
      }
      return View(pilot);
    }

    [Roles(DefaultRoles.Max, DefaultRoles.Med)]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,BirthDate,Genre")] Pilot pilot)
    {
      if (id != pilot.Id)
      {
        return NotFound();
      }

      if (ModelState.IsValid)
      {
        try
        {
          _context.Update(pilot);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!PilotExists(pilot.Id))
          {
            return NotFound();
          }
          else
          {
            throw;
          }
        }
        return RedirectToAction(nameof(Index));
      }
      return View(pilot);
    }

    [Roles(DefaultRoles.Max)]
    public async Task<IActionResult> Delete(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var pilot = await _context.Pilots
          .FirstOrDefaultAsync(m => m.Id == id);
      if (pilot == null)
      {
        return NotFound();
      }

      return View(pilot);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Roles(DefaultRoles.Max)]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
      var pilot = await _context.Pilots.FindAsync(id);
      _context.Pilots.Remove(pilot);
      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool PilotExists(Guid id)
    {
      return _context.Pilots.Any(e => e.Id == id);
    }
  }
}

SecurityWebApp/Controllers/StarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SecurityWebApp.Attributes;
using SecurityWebApp.Data;
using SecurityWebApp.Data.Model;

namespace SecurityWebApp.Controllers
{
  [Authorize]
  public class StarsController : Controller
  {
    private readonly ApplicationDbContext _context;
    private readonly ILogger<StarsController> _logger;

    public StarsController(ApplicationDbContext context, ILogger<StarsController> logger)
    {
      _context = context;
      _logger  = logger;
    }

    public async Task<IActionResult> Index()
    {
      return View(await _context.Stars.ToListAsync());
    }

    [Roles(DefaultRoles.Max, DefaultRoles.Med)]
    public IActionResult Create()
    {
      return View();
    }

    // POST: Stars/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [Roles(DefaultRoles.Max, DefaultRoles.Med)]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,Class")] Star star)
    {
      if (ModelState.IsValid)
      {
        star.Id = Guid.NewGuid();
        _context.Add(star);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }
      return View(star);
    }

    
    [Roles(DefaultRoles.Max, DefaultRoles.Med)]
    public async Task<IActionResult> Edit(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var star = await _context.Stars.FindAsync(id);
      if (star == null)
      {
        return NotFound();
      }
      return View(star);
    }

    // POST: Stars/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Roles(DefaultRoles.Max, DefaultRoles.Med)]
    public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Class")] Star star)
    {
      if (id != star.Id)
      {
        return NotFound();
      }

      if (ModelState.IsValid)
      {
        try
        {
          _context.Update(star);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!StarExists(star.Id))
          {
            return NotFound();
          }
          else
          {
            throw;
          }
        }
        return RedirectToAction(nameof(Index));
      }
      return View(star);
    }

    [Roles(DefaultRoles.Max, DefaultRoles.Med)]
    public async Task<IActionResult> Delete(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var star = await _context.Stars
          .FirstOrDefaultAsync(m => m.Id == id);
      if (star == null)
      {
        return NotFound();
      }

      return View(star);
    }

    [HttpPost, ActionName("Delete")]
    [Roles(DefaultRoles.Max, DefaultRoles.Med)]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
      var star = await _context.Stars.FindAsync(id);
      _context.Stars.Remove(star);
      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool StarExists(Guid id)
    {
      return _context.Stars.Any(e => e.Id == id);
    }
  }
}

SecurityWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - Segurança</title>

  <environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
  </environment>
  <environment exclude="Development">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
          crossorigin="anonymous"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
  </environment>
  <link rel="stylesheet" href="~/css/site.css" />
  <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" />
  <environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
  </environment>
  <environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
    </script>
  </environment>
</head>
<body>
  <script src="~/js/site.js" asp-append-version="true"></script>
  <script src="~/lib/fontawesome/js/all.js" asp-append-version="true"></script>

  @RenderSection("Scripts", required: false)

  <header>
    <nav class="navbar navbar-expand-lg navbar-light border-bottom box-shadow mb-3">
      <a class="navbar-toggler rounded-circle" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-label="Toggle navigation" style="cursor: pointer;">
        <div>
          <i class="fas fa-angle-double-down"></i>
        </div>
      </a>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav justify-content-between w-100">
          <li>
            <a class="navbar-brand nav-link" asp-area="" asp-controller="Home" asp-action="Index">
              <i class="fas fa-rocket"></i> Home
            </a>
          </li>
          <li>
            <a class="nav-link" asp-area="" asp-controller="Stars" asp-action="Index">
              <i class="fas fa-globe-europe"></i> Astros
            </a>
          </li>
          <li>
            <a class="nav-link" asp-area="" asp-controller="Shuttles" asp-action="Index">
              <i class="fas fa-space-shuttle"></i> Espaçonaves
            </a>
          </li>
          <li>
            <a class="nav-link" asp-area="" asp-controller="Pilots" asp-action="Index">
              <i class="fas fa-user-astronaut"></i> Pilotos
            </a>
          </li>
          <li>
            <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index">
              <i class="fas fa-user-friends"></i> Usuários
            </a>
          </li>
          <li>
            <a class="nav-link" asp-area="" asp-controller="Log" asp-action="Index">
              <i class="fas fa-exclamation-triangle"></i> Logs
            </a>
          </li>

          <partial name="_LoginPartial" />
        </ul>

        <div class="d-flex flex-row collapse flex-grow-1 justify-content-center align-items-center justify-content-start">

        </div>
      </div>
    </nav>
  </header>

  <div class="container" id="main-container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-muted">
    <div class="container text-purple font-weight-bold text-center">
      &copy; 2019 - Segurança de Aplicações, Vicenzo & Samuel
    </div>
  </footer>
</body>
</html>